name: CI

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"
        continue-on-error: true

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Setup google credentials
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/gcloud.json
        continue-on-error: true

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"
        continue-on-error: true

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43.0

      - name: Test
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage reports
          path: |
            coverage.out
            coverage.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

      - name: environment variables
        uses: FranzDiebold/github-env-vars-action@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1
        with:
          args: >
            -Dsonar.organization=calyptia
            -Dsonar.projectKey=${{ env.CI_REPOSITORY_NAME_SLUG }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=coverage.out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true